# -*- coding: utf-8 -*-
"""application.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYBsjQHwoSSjmg7ZErwPC03wvJf06RjU
"""

from flask import Flask
from flask import jsonify
import numpy as np

application =Flask(__name__)
@application.route('/')

def hello():

  return 'Hello Bhaswar\n'

@application.route('/random/<n>')


def randomvalues(n):

  values=np.random.randint(0,10,int(n))
  result={'values': values.tolist()}
  return jsonify(result)



if __name__=='__main__':

  application.run(debug = True)

